# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_versal_cips_0_0/design_1_versal_cips_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_versal_cips_0_0 || ORIG_REF_NAME==design_1_versal_cips_0_0} -quiet] -quiet

# Block Designs: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/bd_70da.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_70da || ORIG_REF_NAME==bd_70da} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/bd_70da_pspmc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_70da_pspmc_0_0 || ORIG_REF_NAME==bd_70da_pspmc_0_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/ip_0/versal_cips_ps_vip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_cips_ps_vip_0 || ORIG_REF_NAME==versal_cips_ps_vip_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_noc_0_0 || ORIG_REF_NAME==design_1_axi_noc_0_0} -quiet] -quiet

# Block Designs: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/bd_8be5.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5 || ORIG_REF_NAME==bd_8be5} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/bd_8be5_S02_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S02_AXI_nmu_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_1/bd_8be5_const_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_const_0_0 || ORIG_REF_NAME==bd_8be5_const_0_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/bd_8be5_S00_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S00_AXI_nmu_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/bd_8be5_S03_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S03_AXI_nmu_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/bd_8be5_S01_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S01_AXI_nmu_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/bd_8be5_M03_AXI_nsu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_M03_AXI_nsu_0 || ORIG_REF_NAME==bd_8be5_M03_AXI_nsu_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/bd_8be5_M00_AXI_nsu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_M00_AXI_nsu_0 || ORIG_REF_NAME==bd_8be5_M00_AXI_nsu_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/bd_8be5_M02_AXI_nsu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_M02_AXI_nsu_0 || ORIG_REF_NAME==bd_8be5_M02_AXI_nsu_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/bd_8be5_M01_AXI_nsu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_M01_AXI_nsu_0 || ORIG_REF_NAME==bd_8be5_M01_AXI_nsu_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/bd_8be5_MC0_ddrc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC0_ddrc_0 || ORIG_REF_NAME==bd_8be5_MC0_ddrc_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/bd_8be5_MC0_ddrc_0_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC0_ddrc_0_phy || ORIG_REF_NAME==bd_8be5_MC0_ddrc_0_phy} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_10/bd_8be5_S02_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S02_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S02_AXI_nsw_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_11/bd_8be5_M02_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_M02_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_M02_AXI_nsw_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_12/bd_8be5_MC2_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC2_nsw_0 || ORIG_REF_NAME==bd_8be5_MC2_nsw_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_13/bd_8be5_S00_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S00_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S00_AXI_nsw_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_14/bd_8be5_MC0_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC0_nsw_0 || ORIG_REF_NAME==bd_8be5_MC0_nsw_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_15/bd_8be5_M00_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_M00_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_M00_AXI_nsw_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_16/bd_8be5_S03_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S03_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S03_AXI_nsw_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_17/bd_8be5_M03_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_M03_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_M03_AXI_nsw_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_18/bd_8be5_MC3_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC3_nsw_0 || ORIG_REF_NAME==bd_8be5_MC3_nsw_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_19/bd_8be5_S01_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S01_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S01_AXI_nsw_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_20/bd_8be5_M01_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_M01_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_M01_AXI_nsw_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_21/bd_8be5_MC1_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC1_nsw_0 || ORIG_REF_NAME==bd_8be5_MC1_nsw_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wizard_0_0/design_1_clk_wizard_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wizard_0_0 || ORIG_REF_NAME==design_1_clk_wizard_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emax6_0_0/design_1_emax6_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_emax6_0_0 || ORIG_REF_NAME==design_1_emax6_0_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_emax6_0_0/src/fpga_bram128/fpga_bram128.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_bram128 || ORIG_REF_NAME==fpga_bram128} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emax6_1_0/design_1_emax6_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_emax6_1_0 || ORIG_REF_NAME==design_1_emax6_1_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_emax6_1_0/src/fpga_bram128/fpga_bram128.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_bram128 || ORIG_REF_NAME==fpga_bram128} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emax6_2_0/design_1_emax6_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_emax6_2_0 || ORIG_REF_NAME==design_1_emax6_2_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_emax6_2_0/src/fpga_bram128/fpga_bram128.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_bram128 || ORIG_REF_NAME==fpga_bram128} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emax6_3_0/design_1_emax6_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_emax6_3_0 || ORIG_REF_NAME==design_1_emax6_3_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_emax6_3_0/src/fpga_bram128/fpga_bram128.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_bram128 || ORIG_REF_NAME==fpga_bram128} -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/bd_70da_pspmc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_70da_pspmc_0_0 || ORIG_REF_NAME==bd_70da_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_3/constraints/usr_constraints.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_70da_pspmc_0_0 || ORIG_REF_NAME==bd_70da_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/bd_70da_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_8be5_S02_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S02_AXI_nmu_0} -quiet] {/bd_8be5_S02_AXI_nmu_0_top_INST } ]/bd_8be5_S02_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_8be5_S00_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S00_AXI_nmu_0} -quiet] {/bd_8be5_S00_AXI_nmu_0_top_INST } ]/bd_8be5_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_8be5_S03_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S03_AXI_nmu_0} -quiet] {/bd_8be5_S03_AXI_nmu_0_top_INST } ]/bd_8be5_S03_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_8be5_S01_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S01_AXI_nmu_0} -quiet] {/bd_8be5_S01_AXI_nmu_0_top_INST } ]/bd_8be5_S01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/xdc/bd_8be5_M03_AXI_nsu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_M03_AXI_nsu_0 || ORIG_REF_NAME==bd_8be5_M03_AXI_nsu_0} -quiet] {/bd_8be5_M03_AXI_nsu_0_top_INST } ]/bd_8be5_M03_AXI_nsu_0_top_INST ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/xdc/bd_8be5_M00_AXI_nsu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_M00_AXI_nsu_0 || ORIG_REF_NAME==bd_8be5_M00_AXI_nsu_0} -quiet] {/bd_8be5_M00_AXI_nsu_0_top_INST } ]/bd_8be5_M00_AXI_nsu_0_top_INST ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/xdc/bd_8be5_M02_AXI_nsu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_M02_AXI_nsu_0 || ORIG_REF_NAME==bd_8be5_M02_AXI_nsu_0} -quiet] {/bd_8be5_M02_AXI_nsu_0_top_INST } ]/bd_8be5_M02_AXI_nsu_0_top_INST ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/xdc/bd_8be5_M01_AXI_nsu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_M01_AXI_nsu_0 || ORIG_REF_NAME==bd_8be5_M01_AXI_nsu_0} -quiet] {/bd_8be5_M01_AXI_nsu_0_top_INST } ]/bd_8be5_M01_AXI_nsu_0_top_INST ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/hdl/par/bd_8be5_MC0_ddrc_0_ip.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_MC0_ddrc_0 || ORIG_REF_NAME==bd_8be5_MC0_ddrc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_noc_0_0 || ORIG_REF_NAME==design_1_axi_noc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_noc_0_0 || ORIG_REF_NAME==design_1_axi_noc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_clk_wizard_0_0/design_1_clk_wizard_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wizard_0_0 || ORIG_REF_NAME==design_1_clk_wizard_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_clk_wizard_0_0/design_1_clk_wizard_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wizard_0_0 || ORIG_REF_NAME==design_1_clk_wizard_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_clk_wizard_0_0/design_1_clk_wizard_0_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_emax6_0_0/src/fpga_bram128/fpga_bram128_waivers.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fpga_bram128 || ORIG_REF_NAME==fpga_bram128} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_emax6_0_0/src/fpga_bram128/fpga_bram128_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_emax6_1_0/src/fpga_bram128/fpga_bram128_waivers.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fpga_bram128 || ORIG_REF_NAME==fpga_bram128} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_emax6_1_0/src/fpga_bram128/fpga_bram128_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_emax6_2_0/src/fpga_bram128/fpga_bram128_waivers.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fpga_bram128 || ORIG_REF_NAME==fpga_bram128} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_emax6_2_0/src/fpga_bram128/fpga_bram128_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_emax6_3_0/src/fpga_bram128/fpga_bram128_waivers.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fpga_bram128 || ORIG_REF_NAME==fpga_bram128} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/ip/design_1_emax6_3_0/src/fpga_bram128/fpga_bram128_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VPK180-step4000/VPK180_32st.gen/sources_1/bd/design_1/design_1_ooc.xdc
