
#########
create_clock -period 5.0 [get_ports sys_clk_p]
########
set_property IOSTANDARD LVSTL_11 [get_ports {ch0_lpddr4_dq_a[*] ch0_lpddr4_ca_a[*] ch0_lpddr4_cs_a[*]}]
set_property IOSTANDARD LVSTL_11 [get_ports {ch0_lpddr4_cke_a[*]}]
set_property EQUALIZATION EQ_LEVEL3  [get_ports {ch0_lpddr4_dq_a[*] ch0_lpddr4_dqs_t_a[*] ch0_lpddr4_dqs_c_a[*]}]

set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {ch0_lpddr4_dqs_t_a[*] ch0_lpddr4_dqs_c_a[*] ch0_lpddr4_ck_t_a[*] ch0_lpddr4_ck_c_a[*]}]
set_property ODT RTT_40 [get_ports {ch0_lpddr4_dq_a[*] ch0_lpddr4_dqs_t_a[*] ch0_lpddr4_dqs_c_a[*]}]  
set_property OFFSET_CNTRL CNTRL_NONE [get_ports {ch0_lpddr4_dq_a[*] ch0_lpddr4_dqs_t_a[*] ch0_lpddr4_dqs_c_a[*]}]  
set_property SLEW FAST  [get_ports {ch0_lpddr4_dq_a[*] ch0_lpddr4_dqs_t_a[*] ch0_lpddr4_dqs_c_a[*] ch0_lpddr4_ca_a[*] ch0_lpddr4_cs_a[*] ch0_lpddr4_ck_t_a[*] ch0_lpddr4_ck_c_a[*] ch0_lpddr4_cke_a[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ch0_lpddr4_dq_a[*] ch0_lpddr4_dqs_t_a[*] ch0_lpddr4_dqs_c_a[*] ch0_lpddr4_ca_a[*] ch0_lpddr4_cs_a[*] ch0_lpddr4_ck_t_a[*] ch0_lpddr4_ck_c_a[*] ch0_lpddr4_cke_a[*]}]
set_property VOH 50  [get_ports {ch0_lpddr4_dq_a[*] ch0_lpddr4_dqs_t_a[*] ch0_lpddr4_dqs_c_a[*] ch0_lpddr4_ca_a[*] ch0_lpddr4_cs_a[*] ch0_lpddr4_ck_t_a[*] ch0_lpddr4_ck_c_a[*] ch0_lpddr4_cke_a[*]}]
######
set_property IOSTANDARD LVSTL_11 [get_ports {ch0_lpddr4_dmi_a[*]}]
set_property ODT RTT_40 [get_ports {ch0_lpddr4_dmi_a[*]}]
set_property SLEW FAST [get_ports {ch0_lpddr4_dmi_a[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ch0_lpddr4_dmi_a[*]}]
set_property OFFSET_CNTRL CNTRL_NONE [get_ports {ch0_lpddr4_dmi_a[*]}]
set_property VOH 50 [get_ports {ch0_lpddr4_dmi_a[*]}]
set_property EQUALIZATION EQ_LEVEL3 [get_ports {ch0_lpddr4_dmi_a[*]}]
#############
set_property IOSTANDARD LVSTL_11 [get_ports {ch0_lpddr4_dq_b[*]}]
set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {ch0_lpddr4_dqs_t_b[*] ch0_lpddr4_dqs_c_b[*]}]
set_property ODT RTT_40 [get_ports {ch0_lpddr4_dq_b[*] ch0_lpddr4_dqs_t_b[*] ch0_lpddr4_dqs_c_b[*]}]  
set_property SLEW FAST  [get_ports {ch0_lpddr4_dq_b[*] ch0_lpddr4_dqs_t_b[*] ch0_lpddr4_dqs_c_b[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ch0_lpddr4_dq_b[*] ch0_lpddr4_dqs_t_b[*] ch0_lpddr4_dqs_c_b[*]}]
set_property OFFSET_CNTRL CNTRL_NONE [get_ports {ch0_lpddr4_dq_b[*] ch0_lpddr4_dqs_t_b[*] ch0_lpddr4_dqs_c_b[*]}]  
set_property VOH 50 [get_ports {ch0_lpddr4_dq_b[*] ch0_lpddr4_dqs_t_b[*] ch0_lpddr4_dqs_c_b[*]}]
set_property EQUALIZATION EQ_LEVEL3 [get_ports {ch0_lpddr4_dq_b[*] ch0_lpddr4_dqs_t_b[*] ch0_lpddr4_dqs_c_b[*]}]
#####
set_property IOSTANDARD LVSTL_11 [get_ports {ch0_lpddr4_dmi_b[*]}]
set_property ODT RTT_40 [get_ports {ch0_lpddr4_dmi_b[*]}]
set_property SLEW FAST [get_ports {ch0_lpddr4_dmi_b[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ch0_lpddr4_dmi_b[*]}]
set_property OFFSET_CNTRL CNTRL_NONE [get_ports {ch0_lpddr4_dmi_b[*]}]
set_property VOH 50 [get_ports {ch0_lpddr4_dmi_b[*]}]
set_property EQUALIZATION EQ_LEVEL3 [get_ports {ch0_lpddr4_dmi_b[*]}]
######
set_property IOSTANDARD LVSTL_11 [get_ports {ch0_lpddr4_ca_b[*] ch0_lpddr4_cs_b[*]}]
set_property IOSTANDARD LVSTL_11 [get_ports {ch0_lpddr4_cke_b[*]}]
set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {ch0_lpddr4_ck_t_b[*] ch0_lpddr4_ck_c_b[*]}]
set_property SLEW FAST  [get_ports {ch0_lpddr4_ca_b[*] ch0_lpddr4_cs_b[*] ch0_lpddr4_ck_t_b[*] ch0_lpddr4_ck_c_b[*] ch0_lpddr4_cke_b[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ch0_lpddr4_ca_b[*] ch0_lpddr4_cs_b[*] ch0_lpddr4_ck_t_b[*] ch0_lpddr4_ck_c_b[*] ch0_lpddr4_cke_b[*]}]
set_property VOH 50 [get_ports {ch0_lpddr4_ca_b[*] ch0_lpddr4_cs_b[*] ch0_lpddr4_ck_t_b[*] ch0_lpddr4_ck_c_b[*] ch0_lpddr4_cke_b[*]}]
######
set_property IOSTANDARD LVSTL_11 [get_ports {ch0_lpddr4_reset_n}]
set_property VOH 50 [get_ports {ch0_lpddr4_reset_n}]
###set_property SLEW FAST  [get_ports {ch0_lpddr4_reset_n}]
###set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ch0_lpddr4_reset_n}]
######
set_property IOSTANDARD LVSTL_11 [get_ports {ch1_lpddr4_dq_a[*] ch1_lpddr4_ca_a[*] ch1_lpddr4_cs_a[*]}]
set_property IOSTANDARD LVSTL_11 [get_ports {ch1_lpddr4_cke_a[*]}]
set_property EQUALIZATION EQ_LEVEL3 [get_ports {ch1_lpddr4_dq_a[*] ch1_lpddr4_dqs_t_a[*] ch1_lpddr4_dqs_c_a[*]}]
set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {ch1_lpddr4_dqs_t_a[*] ch1_lpddr4_dqs_c_a[*] ch1_lpddr4_ck_t_a[*] ch1_lpddr4_ck_c_a[*]}]
set_property OFFSET_CNTRL CNTRL_NONE [get_ports {ch1_lpddr4_dq_a[*] ch1_lpddr4_dqs_t_a[*] ch1_lpddr4_dqs_c_a[*]}]  
set_property ODT RTT_40 [get_ports {ch1_lpddr4_dq_a[*] ch1_lpddr4_dqs_t_a[*] ch1_lpddr4_dqs_c_a[*]}]  
set_property SLEW FAST  [get_ports {ch1_lpddr4_dq_a[*] ch1_lpddr4_dqs_t_a[*] ch1_lpddr4_dqs_c_a[*] ch1_lpddr4_ca_a[*] ch1_lpddr4_cs_a[*] ch1_lpddr4_ck_t_a[*] ch1_lpddr4_ck_c_a[*] ch1_lpddr4_cke_a[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ch1_lpddr4_dq_a[*] ch1_lpddr4_dqs_t_a[*] ch1_lpddr4_dqs_c_a[*] ch1_lpddr4_ca_a[*] ch1_lpddr4_cs_a[*] ch1_lpddr4_ck_t_a[*] ch1_lpddr4_ck_c_a[*] ch1_lpddr4_cke_a[*]}]
set_property VOH 50  [get_ports {ch1_lpddr4_dq_a[*] ch1_lpddr4_dqs_t_a[*] ch1_lpddr4_dqs_c_a[*] ch1_lpddr4_ca_a[*] ch1_lpddr4_cs_a[*] ch1_lpddr4_ck_t_a[*] ch1_lpddr4_ck_c_a[*] ch1_lpddr4_cke_a[*]}]
######
set_property IOSTANDARD LVSTL_11 [get_ports {ch1_lpddr4_dmi_a[*]}]
set_property ODT RTT_40 [get_ports {ch1_lpddr4_dmi_a[*]}]
set_property SLEW FAST [get_ports {ch1_lpddr4_dmi_a[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ch1_lpddr4_dmi_a[*]}]
set_property OFFSET_CNTRL CNTRL_NONE [get_ports {ch1_lpddr4_dmi_a[*]}]
set_property VOH 50 [get_ports {ch1_lpddr4_dmi_a[*]}]
set_property EQUALIZATION EQ_LEVEL3 [get_ports {ch1_lpddr4_dmi_a[*]}]
######
set_property IOSTANDARD LVSTL_11 [get_ports {ch1_lpddr4_dq_b[*]}]
set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {ch1_lpddr4_dqs_t_b[*] ch1_lpddr4_dqs_c_b[*]}]
set_property ODT RTT_40 [get_ports {ch1_lpddr4_dq_b[*] ch1_lpddr4_dqs_t_b[*] ch1_lpddr4_dqs_c_b[*]}]  
set_property SLEW FAST  [get_ports {ch1_lpddr4_dq_b[*] ch1_lpddr4_dqs_t_b[*] ch1_lpddr4_dqs_c_b[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ch1_lpddr4_dq_b[*] ch1_lpddr4_dqs_t_b[*] ch1_lpddr4_dqs_c_b[*]}]
set_property OFFSET_CNTRL CNTRL_NONE [get_ports {ch1_lpddr4_dq_b[*] ch1_lpddr4_dqs_t_b[*] ch1_lpddr4_dqs_c_b[*]}]  
set_property VOH 50 [get_ports {ch1_lpddr4_dq_b[*] ch1_lpddr4_dqs_t_b[*] ch1_lpddr4_dqs_c_b[*]}]
set_property EQUALIZATION EQ_LEVEL3 [get_ports {ch1_lpddr4_dq_b[*] ch1_lpddr4_dqs_t_b[*] ch1_lpddr4_dqs_c_b[*]}]
######
set_property IOSTANDARD LVSTL_11 [get_ports {ch1_lpddr4_dmi_b[*]}]
set_property ODT RTT_40 [get_ports {ch1_lpddr4_dmi_b[*]}]
set_property SLEW FAST [get_ports {ch1_lpddr4_dmi_b[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ch1_lpddr4_dmi_b[*]}]
set_property OFFSET_CNTRL CNTRL_NONE [get_ports {ch1_lpddr4_dmi_b[*]}]
set_property VOH 50 [get_ports {ch1_lpddr4_dmi_b[*]}]
set_property EQUALIZATION EQ_LEVEL3 [get_ports {ch1_lpddr4_dmi_b[*]}]
######
set_property IOSTANDARD LVSTL_11 [get_ports {ch1_lpddr4_ca_b[*] ch1_lpddr4_cs_b[*]}]
set_property IOSTANDARD LVSTL_11 [get_ports {ch1_lpddr4_cke_b[*]}]
set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {ch1_lpddr4_ck_t_b[*] ch1_lpddr4_ck_c_b[*]}]
set_property SLEW FAST  [get_ports {ch1_lpddr4_ca_b[*] ch1_lpddr4_cs_b[*] ch1_lpddr4_ck_t_b[*] ch1_lpddr4_ck_c_b[*] ch1_lpddr4_cke_b[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ch1_lpddr4_ca_b[*] ch1_lpddr4_cs_b[*] ch1_lpddr4_ck_t_b[*] ch1_lpddr4_ck_c_b[*] ch1_lpddr4_cke_b[*]}]
set_property VOH 50 [get_ports {ch1_lpddr4_ca_b[*] ch1_lpddr4_cs_b[*] ch1_lpddr4_ck_t_b[*] ch1_lpddr4_ck_c_b[*] ch1_lpddr4_cke_b[*]}]
######
set_property IOSTANDARD LVSTL_11 [get_ports {ch1_lpddr4_reset_n}]
set_property VOH 50 [get_ports {ch1_lpddr4_reset_n}]
###set_property DRIVE 8 [get_ports {ch1_lpddr4_reset_n}]
###set_property SLEW FAST  [get_ports {ch1_lpddr4_reset_n}]
###set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ch1_lpddr4_reset_n}]
######
set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {sys_clk_p sys_clk_n}]
set_property EQUALIZATION EQ_LEVEL3 [get_ports {sys_clk_p sys_clk_n}]
set_property ODT RTT_NONE [get_ports {sys_clk_p sys_clk_n}]

